services:
  sql:
    image: mcr.microsoft.com/mssql/server
    container_name: sql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password@1
      - MSSQL-PID=Developer
    ports:
      - 1433:1433
